// Shared style rules and a post-processing sanitiser so nothing generated by
// the LLM screams "written by AI". Plug HUMAN_STYLE_RULES into any prompt
// that produces prose the user will see; run sanitizeProse() on the output
// as a safety net so slips never reach the CV or email.

export const HUMAN_STYLE_RULES = `Style rules — this must not read like AI-written copy:
- Do NOT use em dashes (—) or en dashes (–) in prose. Use commas, colons, brackets, or two shorter sentences instead. En dashes are still fine in numeric ranges such as date ranges (e.g. "2018–2022").
- Avoid AI-tell phrases: "delve", "delve into", "meticulous", "meticulously", "in the realm of", "navigate the landscape of", "leverage" (use "use"), "utilise" (use "use"), "furthermore", "moreover", "in today's fast-paced world", "seamlessly", "tapestry", "robust" (unless quoting).
- Avoid tricolons for their own sake ("adaptable, resilient and driven") when a plain description works.
- Prefer plain punctuation. If you would have reached for an em dash, use a comma or start a new sentence.
- Do not open sentences with "It's worth noting that" or "It should be noted that".`;

// Post-process AI prose to strip the two dead giveaways the model most often
// slips through despite the instructions above.
//
// Em dashes → replaced with a comma-space (matches the natural pause). We
// squash any resulting double punctuation. En dashes are left alone in
// numeric contexts (date ranges are legitimate typography) and only stripped
// where they sit between word characters as a stylistic pause.
export function sanitizeProse(input: string | undefined | null): string {
  if (!input) return "";
  let out = input;

  // 1) Em dashes: kill everywhere in prose. "text — text" → "text, text".
  out = out.replace(/\s*—\s*/g, ", ");

  // 2) En dashes: strip only when used stylistically between letters
  // (e.g. "closes deals – wins clients"). Preserve numeric ranges like
  // "2018–2022" and "9am–5pm".
  out = out.replace(/(?<=[A-Za-z])\s*–\s*(?=[A-Za-z])/g, ", ");

  // 3) Fold any doubled-up punctuation the substitutions created.
  out = out
    .replace(/,\s*,+/g, ",") //  ", ,"  →  ","
    .replace(/,\s*\./g, ".") //  ", ."  →  "."
    .replace(/\.\s*,/g, ".") //  ". ,"  →  "."
    .replace(/\s{2,}/g, " ") //  collapse runs of spaces
    .replace(/\s+([,.;:!?])/g, "$1"); //  " ," → ","

  return out.trim();
}

// Same idea but for arrays of short strings (skills, bullets, qualifications).
export function sanitizeProseList(items: string[] | undefined | null): string[] {
  if (!items) return [];
  return items.map((s) => sanitizeProse(s)).filter((s) => s.length > 0);
}
